import { jsPDF } from 'jspdf';
import type { AuditResult } from '../types';
import { getScoreColor, getScoreLabel } from './pagespeed';

export async function generatePDF(audit: AuditResult): Promise<void> {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let y = margin;

  pdf.setFillColor(10, 10, 15);
  pdf.rect(0, 0, pageWidth, pdf.internal.pageSize.getHeight(), 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(28);
  pdf.text('AuraSEO', margin, y + 10);
  
  pdf.setFontSize(12);
  pdf.setTextColor(160, 160, 176);
  pdf.text('Performance Audit Report', margin, y + 18);

  y += 35;

  pdf.setFontSize(14);
  pdf.setTextColor(255, 255, 255);
  pdf.text('Target URL', margin, y);
  pdf.setFontSize(11);
  pdf.setTextColor(103, 78, 188);
  pdf.text(audit.url.length > 60 ? audit.url.substring(0, 57) + '...' : audit.url, margin, y + 6);

  pdf.setFontSize(14);
  pdf.setTextColor(255, 255, 255);
  pdf.text('Device', pageWidth - margin - 40, y);
  pdf.setFontSize(11);
  pdf.setTextColor(141, 134, 201);
  pdf.text(audit.device.charAt(0).toUpperCase() + audit.device.slice(1), pageWidth - margin - 40, y + 6);

  y += 25;

  pdf.setFillColor(18, 18, 26);
  pdf.roundedRect(margin, y, pageWidth - margin * 2, 50, 3, 3, 'F');

  const scores = [
    { label: 'Performance', value: audit.scores.performance },
    { label: 'Accessibility', value: audit.scores.accessibility },
    { label: 'Best Practices', value: audit.scores.bestPractices },
    { label: 'SEO', value: audit.scores.seo },
  ];

  const colWidth = (pageWidth - margin * 2) / 4;
  scores.forEach((score, i) => {
    const x = margin + colWidth * i + colWidth / 2;
    const color = getScoreColor(score.value);
    
    pdf.setFontSize(24);
    const rgb = hexToRgb(color);
    pdf.setTextColor(rgb.r, rgb.g, rgb.b);
    pdf.text(String(score.value), x, y + 20, { align: 'center' });

    pdf.setFontSize(9);
    pdf.setTextColor(160, 160, 176);
    pdf.text(score.label, x, y + 28, { align: 'center' });

    pdf.setFontSize(7);
    pdf.setTextColor(255, 255, 255);
    pdf.text(getScoreLabel(score.value), x, y + 35, { align: 'center' });
  });

  y += 65;

  pdf.setFontSize(14);
  pdf.setTextColor(255, 255, 255);
  pdf.text('Core Web Vitals', margin, y);

  y += 10;
  pdf.setFillColor(18, 18, 26);
  pdf.roundedRect(margin, y, pageWidth - margin * 2, 35, 3, 3, 'F');

  const vitals = [
    { label: 'LCP', value: String(audit.coreVitals.lcp), unit: 'ms' },
    { label: 'FID', value: String(audit.coreVitals.fid), unit: 'ms' },
    { label: 'CLS', value: audit.coreVitals.cls.toFixed(2), unit: '' },
  ];

  const vitalWidth = (pageWidth - margin * 2) / 3;
  vitals.forEach((vital, i) => {
    const x = margin + vitalWidth * i + 15;
    
    pdf.setFontSize(18);
    pdf.setTextColor(255, 255, 255);
    pdf.text(vital.value, x, y + 15);
    
    pdf.setFontSize(9);
    pdf.setTextColor(160, 160, 176);
    pdf.text(vital.label + (vital.unit ? ` (${vital.unit})` : ''), x, y + 23);
  });

  y += 50;

  const critical = audit.audits.critical.slice(0, 5);
  if (critical.length > 0) {
    pdf.setFontSize(14);
    pdf.setTextColor(255, 68, 102);
    pdf.text('Critical Issues', margin, y);
    y += 8;

    pdf.setFontSize(9);
    critical.forEach((item, i) => {
      pdf.setTextColor(255, 255, 255);
      pdf.text(`${i + 1}. ${item.title}`, margin, y);
      y += 5;
    });
  }

  y += 15;
  const warnings = audit.audits.warnings.slice(0, 5);
  if (warnings.length > 0) {
    pdf.setFontSize(14);
    pdf.setTextColor(255, 170, 0);
    pdf.text('Warnings', margin, y);
    y += 8;

    pdf.setFontSize(9);
    warnings.forEach((item, i) => {
      pdf.setTextColor(255, 255, 255);
      pdf.text(`${i + 1}. ${item.title}`, margin, y);
      y += 5;
    });
  }

  y += 20;
  pdf.setFontSize(8);
  pdf.setTextColor(96, 96, 112);
  const date = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  pdf.text(`Generated by AuraSEO on ${date}`, margin, y);

  pdf.save(`AuraSEO-Report-${audit.url.replace(/[^a-zA-Z0-9]/g, '-')}.pdf`);
}

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16),
      }
    : { r: 255, g: 255, b: 255 };
}